package pe.ecocontrol.pachacutin;
import android.annotation.SuppressLint;import android.bluetooth.*;import android.content.*;import android.os.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;
public class ClassicBluetoothController{
 public interface Listener{void onClassicDevices(List<BluetoothDevice>d);void onClassicConnected(BluetoothDevice d);void onClassicDisconnected();void onClassicMessage(String m);void onClassicStatus(String s);void onClassicError(String e);}
 private static final UUID SPP=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");private final Context c;private final Listener l;private final Handler h=new Handler(Looper.getMainLooper());private final ExecutorService io=Executors.newSingleThreadExecutor();private final BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();private final LinkedHashMap<String,BluetoothDevice> found=new LinkedHashMap<>();private BluetoothSocket s;private OutputStream out;private boolean reg;
 public ClassicBluetoothController(Context c,Listener l){this.c=c.getApplicationContext();this.l=l;} public boolean isEnabled(){return a!=null&&a.isEnabled();}
 @SuppressLint("MissingPermission") public void scan(long ms){if(a==null){l.onClassicError("Bluetooth no disponible.");return;}found.clear();for(BluetoothDevice d:a.getBondedDevices())found.put(d.getAddress(),d);register();a.cancelDiscovery();a.startDiscovery();l.onClassicStatus("Buscando HC-05/HC-06…");h.postDelayed(()->{try{a.cancelDiscovery();}catch(Exception ignored){}l.onClassicDevices(new ArrayList<>(found.values()));},ms);}
 @SuppressLint("MissingPermission") private void register(){if(reg)return;IntentFilter f=new IntentFilter();f.addAction(BluetoothDevice.ACTION_FOUND);f.addAction(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);c.registerReceiver(r,f);reg=true;}
 private final BroadcastReceiver r=new BroadcastReceiver(){@SuppressLint("MissingPermission")public void onReceive(Context c,Intent i){if(BluetoothDevice.ACTION_FOUND.equals(i.getAction())){BluetoothDevice d=i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);if(d!=null)found.put(d.getAddress(),d);}else if(BluetoothAdapter.ACTION_DISCOVERY_FINISHED.equals(i.getAction()))l.onClassicDevices(new ArrayList<>(found.values()));}};
 @SuppressLint("MissingPermission") public void connect(BluetoothDevice d){disconnect();l.onClassicStatus("Conectando con "+safeName(d)+"…");io.execute(()->{try{a.cancelDiscovery();BluetoothSocket x=d.createRfcommSocketToServiceRecord(SPP);x.connect();s=x;out=x.getOutputStream();h.post(()->l.onClassicConnected(d));BufferedReader br=new BufferedReader(new InputStreamReader(x.getInputStream(),StandardCharsets.UTF_8));String line;while(x.isConnected()&&(line=br.readLine())!=null){String m=line.trim();if(!m.isEmpty())h.post(()->l.onClassicMessage(m));}}catch(Exception e){h.post(()->l.onClassicError("No se pudo conectar. Empareje con PIN 1234 o 0000. "+e.getMessage()));}finally{close();h.post(l::onClassicDisconnected);}});}
 public boolean send(String cmd){try{if(out==null||s==null||!s.isConnected())return false;out.write((cmd+"\n").getBytes(StandardCharsets.UTF_8));out.flush();return true;}catch(Exception e){l.onClassicError("Error enviando comando: "+e.getMessage());return false;}}
 public void disconnect(){close();}private void close(){try{if(s!=null)s.close();}catch(Exception ignored){}s=null;out=null;}public void release(){disconnect();io.shutdownNow();if(reg)try{c.unregisterReceiver(r);}catch(Exception ignored){}}
 @SuppressLint("MissingPermission") public static String safeName(BluetoothDevice d){try{String n=d.getName();return n==null||n.trim().isEmpty()?"Dispositivo Bluetooth":n;}catch(Exception e){return "Dispositivo Bluetooth";}}
}
